version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secrett
      MYSQL_DATABASE: mensajes_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
