version: '3'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: CONTRASENA
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  memcached:
    image: memcached:latest
    restart: always
    command: ["memcached", "-m", "64"] # Limito el tamaño de la cache a 64 megabytes y le saco el tiempo a cad objeto cargado
    ports:
      - 11211:11211
