version: '3'

services:
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"  # Puerto predeterminado para AMQP
      - "15672:15672"  # Puerto para la interfaz web de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
