version: '3'

services:
  db_usuarios:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secrett
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./data_usuarios:/var/lib/mysql